gpg_core_files_dir: "{{ playbook_dir }}/gpg_remote/gpg_config"
gpg_core_files_remote_dir: "~/.gpg-openshift"
gpg_publickey_file: openshift@example.com
openshift_version: 3.11
openshift_image_management_project_name: image-management
openshift_image_management_project_display_name: Image Management
openshift_image_management_node_label: "image_management=true"
openshift_image_management_node_taint: "image_management=true:NoExecute"
openshift_image_management_gpg_secret_name: gpg
openshift_image_management_sa_name: imagemanager
openshift_sign_pod_template_name: sign-image-pod-template

image_managers_hostgroup: image_managers

signature_viewer_role: signature-viewer

tmp_default_project_template: /tmp/ocp-default-project-template.yml

openshift_configs_dest_dir: "~/ocp-configs"
openshift_base_scan_template: image-sign-scan-base.yml
openshift_policy_template: policies-template.yml
openshift_sign_image_template: sign-image-template.yml
openshift_sign_image_pod_template: sign-image-pod-template.yml
openshift_scan_image_pod_template: scan-image-pod-template.yml
openshift_event_controller_template: event-controller-template.yml

openshift_configs:
- "policy/{{ openshift_policy_template }}"
- "image-sign-scan-base/{{ openshift_base_scan_template }}"
- "sign-image/{{ openshift_sign_image_template }}"
- image-scanning/pipeline.yml
- "image-scanning/{{ openshift_scan_image_pod_template }}"
- "sign-image/{{ openshift_sign_image_pod_template }}"
- "event-controller/{{ openshift_event_controller_template }}"

deploy_eventcontroller: False
